const OTP_TTL = 600;
const SESS_TTL = 28800;
const OTP_MAX_ATTEMPTS = 5;
const OTP_COOLDOWN_SEC = 25;
const OTP_MAX_PER_HOUR = 10;
const CORS = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type,X-Session-Token"};
const ROLE_DEPT = {weaving:"Weaving",dyeing:"Dyeing",finishing:"Finishing",prep:"Prep",gm_tech:"UB",ppc:"PPC",bathrobe:"Bathrobe",quality:"Quality",rsb:"RSB",hr:"HR",hr_noida:"Noida Finishing"};
function json(data, status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...CORS}});}
function rand6(){const a=new Uint32Array(1);crypto.getRandomValues(a);return String(100000+(a[0]%900000));}
function randToken(){const arr=new Uint8Array(32);crypto.getRandomValues(arr);return Array.from(arr).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function sendOTP(mobile,otp,env){try{const url="https://2factor.in/API/V1/"+env.TWOFACTOR_KEY+"/SMS/"+mobile+"/"+otp+"/OTP1";const resp=await fetch(url);const data=await resp.json();return data.Status==="Success";}catch(e){return false;}}
async function getSession(request,env){const token=request.headers.get("X-Session-Token")||new URL(request.url).searchParams.get("token");if(!token)return null;const raw=await env.AUTH_KV.get("sess:"+token);if(!raw)return null;return JSON.parse(raw);}
async function requireAdmin(request,env){const sess=await getSession(request,env);if(!sess||sess.role!=="admin")return null;return sess;}
export default{async fetch(request,env){
const url=new URL(request.url);const path=url.pathname;
if(request.method==="OPTIONS")return new Response(null,{headers:CORS});
if(path==="/auth/send-otp"&&request.method==="POST"){const{mobile}=await request.json();if(!mobile||!/^[6-9]\d{9}$/.test(mobile))return json({ok:false,error:"Invalid mobile number"},400);const userRaw=await env.AUTH_KV.get("user:"+mobile);if(!userRaw)return json({ok:false,error:"Number not registered. Contact admin."},403);const now=Date.now();const rlRaw=await env.AUTH_KV.get("otprl:"+mobile);let rl=rlRaw?JSON.parse(rlRaw):{n:0,first:now,last:0};if(now-rl.first>3600000)rl={n:0,first:now,last:0};if(rl.last&&now-rl.last<OTP_COOLDOWN_SEC*1000)return json({ok:false,error:"Please wait a few seconds before requesting another OTP."},429);if(rl.n>=OTP_MAX_PER_HOUR)return json({ok:false,error:"Too many OTP requests. Please try again later."},429);const otp=rand6();await env.AUTH_KV.put("otp:"+mobile,otp,{expirationTtl:OTP_TTL});await env.AUTH_KV.delete("otpat:"+mobile);const sent=await sendOTP(mobile,otp,env);if(!sent)return json({ok:false,error:"SMS failed - please retry"},500);rl.n++;rl.last=now;await env.AUTH_KV.put("otprl:"+mobile,JSON.stringify(rl),{expirationTtl:3600});return json({ok:true});}
if(path==="/auth/verify-otp"&&request.method==="POST"){const{mobile,otp}=await request.json();if(!mobile||!otp)return json({ok:false,error:"Missing fields"},400);const atRaw=await env.AUTH_KV.get("otpat:"+mobile);const at=atRaw?parseInt(atRaw,10):0;if(at>=OTP_MAX_ATTEMPTS){await env.AUTH_KV.delete("otp:"+mobile);return json({ok:false,error:"Too many incorrect attempts. Please request a new OTP."},429);}const stored=await env.AUTH_KV.get("otp:"+mobile);if(!stored||stored!==otp){await env.AUTH_KV.put("otpat:"+mobile,String(at+1),{expirationTtl:OTP_TTL});return json({ok:false,error:"Incorrect or expired OTP"},401);}const userRaw=await env.AUTH_KV.get("user:"+mobile);if(!userRaw)return json({ok:false,error:"Number not registered. Contact admin."},403);await env.AUTH_KV.delete("otp:"+mobile);await env.AUTH_KV.delete("otpat:"+mobile);const user=JSON.parse(userRaw);const token=randToken();const sess={mobile,role:user.role,name:user.name,dept:user.dept||null,created:Date.now()};await env.AUTH_KV.put("sess:"+token,JSON.stringify(sess),{expirationTtl:SESS_TTL});user.lastLogin=new Date().toISOString();await env.AUTH_KV.put("user:"+mobile,JSON.stringify(user));return json({ok:true,token,role:user.role,name:user.name,dept:user.dept||null});}
if(path==="/auth/session"&&request.method==="GET"){const sess=await getSession(request,env);if(!sess)return json({ok:false,error:"Invalid or expired session"},401);return json({ok:true,role:sess.role,name:sess.name,dept:sess.dept,mobile:sess.mobile});}
if(path==="/auth/logout"&&request.method==="POST"){const token=request.headers.get("X-Session-Token");if(token)await env.AUTH_KV.delete("sess:"+token);return json({ok:true});}
if(path.startsWith("/kpidata/")&&request.method==="GET"){const sess=await getSession(request,env);if(!sess)return json({ok:false,error:"Unauthorized"},401);const parts=path.split("/");const dept=decodeURIComponent(parts[2]);const mk=decodeURIComponent(parts[3]);const raw=await env.AUTH_KV.get("kpidata:"+dept+":"+mk);return json({ok:true,data:raw?JSON.parse(raw):{}});}
if(path.startsWith("/kpidata/")&&request.method==="POST"){const sess=await getSession(request,env);if(!sess)return json({ok:false,error:"Unauthorized"},401);const parts=path.split("/");const dept=decodeURIComponent(parts[2]);const mk=decodeURIComponent(parts[3]);const sessDept=sess.dept||ROLE_DEPT[sess.role]||null;if(sess.role!=="admin"&&sessDept!==dept)return json({ok:false,error:"Forbidden"},403);const{data}=await request.json();await env.AUTH_KV.put("kpidata:"+dept+":"+mk,JSON.stringify(data));return json({ok:true});}
if(path==="/admin/users"&&request.method==="GET"){if(!await requireAdmin(request,env))return json({ok:false,error:"Unauthorized"},401);const list=await env.AUTH_KV.list({prefix:"user:"});const users=await Promise.all(list.keys.map(async k=>{const raw=await env.AUTH_KV.get(k.name);return raw?JSON.parse(raw):null;}));return json({ok:true,users:users.filter(Boolean)});}
if(path==="/admin/users"&&request.method==="POST"){if(!await requireAdmin(request,env))return json({ok:false,error:"Unauthorized"},401);const{mobile,name,role,dept}=await request.json();if(!mobile||!name||!role)return json({ok:false,error:"Missing fields"},400);const user={mobile,name,role,dept:dept||null,added:new Date().toISOString(),lastLogin:null};await env.AUTH_KV.put("user:"+mobile,JSON.stringify(user));return json({ok:true,user});}
if(path.startsWith("/admin/users/")&&request.method==="DELETE"){if(!await requireAdmin(request,env))return json({ok:false,error:"Unauthorized"},401);await env.AUTH_KV.delete("user:"+path.split("/").pop());return json({ok:true});}
if(path.startsWith("/manpower/")&&request.method==="GET"){const sess=await getSession(request,env);if(!sess)return json({ok:false,error:"Unauthorized"},401);const date=path.split("/")[2];const raw=await env.AUTH_KV.get("manpower:"+date);return json({ok:true,data:raw?JSON.parse(raw):null});}
if(path.startsWith("/manpower/")&&request.method==="POST"){const sess=await getSession(request,env);if(!sess)return json({ok:false,error:"Unauthorized"},401);const date=path.split("/")[2];const data=await request.json();await env.AUTH_KV.put("manpower:"+date,JSON.stringify({...data,enteredBy:sess.mobile,enteredAt:new Date().toISOString()}));return json({ok:true});}if(path==="/manpower-range"&&request.method==="GET"){const s=url.searchParams.get("start");const e=url.searchParams.get("end");if(!s||!e)return json({ok:false,error:"Missing params"},400);const keys=[];let d=new Date(s+"T00:00:00Z");const ed=new Date(e+"T00:00:00Z");while(d<=ed&&keys.length<35){keys.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1);}const entries=await Promise.all(keys.map(async k=>{const raw=await env.AUTH_KV.get("manpower:"+k);return{date:k,data:raw?JSON.parse(raw):null};}));return json({ok:true,data:entries});}
return json({ok:false,error:"Not found"},404);}};
